
services:

  backend:   
    build: .
    ports:
      - 3001:3001            # A porta da direita precisa ser igual a da variável PORT.
    depends_on:
      - database
    environment:
      - DB_HOST=database     # Se mudar valor dessa variável, tem que mudar o nome do serviço "database" igualmente E VICE-VERSA; remover nem pensar.  
      - DB_NAME=GamesStore    
      - PORT=3001
    volumes:
      - .:/myapp
    networks:
      - games-store 

  database:
    build: models/
    networks:
      - games-store 


networks:
  games-store:
    name: games-store
