
# Variável definida em arquivo compose ou em outras maneiras de criação de containe , ... 
# ... terá prioridade em relação a mesma variável ser definida em um dockerfile.
# Fiz essa "dança de portas" proposital; quis testar diversas combinações possíveis a caráter de estudo e teste.

services:
  backend:   
    build: .
    ports:
      - 3003:3006            # A porta da direita precisa ser gual a da variável PORT abaixo (linha 17). 
    depends_on:
      - database
    networks:
      - app-game-2 
    environment:
      - DB_HOST=database
      - DB_NAME=GamesStore  
      - PORT=3006
  database:
    build: models/
    networks:
      - app-game-2 
networks:
  app-game-2: 
