services:
  backend:   
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - app-game-2 
    environment:
      - DB_HOST=database
  database:
    build: models/
    networks:
      - app-game-2 
   
networks:
  app-game-2: 
